import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import Head from "next/head";
import { api } from "~/utils/api";
import { DataContext } from "../components/data_context";
import "~/styles/globals.css";
import Link from "next/link";

import { ChakraProvider } from "@chakra-ui/react";
const Navbar = () => {
  const router = useRouter();
  const linkClass = (href: string) =>
    router.pathname === href
      ? "text-primary whitespace-nowrap border-b pb-2 pt-1 font-semibold leading-none transition sm:px-2 active-link"
      : "text-primary whitespace-nowrap border-b border-transparent pb-2 pt-1 leading-none transition hover:border-gray-300 dark:hover:border-gray-600 sm:px-2";

  return (
    <div className="navbar bg-primary text-primary relative z-40 border-b px-3 text-white sm:px-6">
      <div className="container mx-auto flex items-center justify-between">
        <h1 className="font-bold">T3 App</h1>
        <div className="-mb-px flex space-x-3 overflow-x-auto sm:space-x-0">
          <Link className={linkClass("/")} href="/">
            Dashboard
          </Link>
          <Link className={linkClass("/transactions")} href="/transactions">
            Transactions
          </Link>
          <Link
            className={linkClass("/api/auth/signin")}
            href="/api/auth/signin"
          >
            Sign out
          </Link>
        </div>
      </div>
    </div>
  );
};
import { useEffect, useState } from "react";
import { Transaction } from "../components/types";
import { useRouter } from "next/router";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const [data, setData] = useState<Transaction[] | null>(null);
  const { data: categories } = api.category.getAll.useQuery();
  // Load data from localStorage when component mounts
  useEffect(() => {
    const savedData = localStorage.getItem("data");
    if (savedData && savedData.length > 0) {
      setData(JSON.parse(savedData) as Transaction[]);
    }
  }, []);

  // Save data to localStorage whenever it changes
  useEffect(() => {
    if (data === null) {
      return;
    }
    localStorage.setItem("data", JSON.stringify(data));
  }, [data]);
  return (
    <SessionProvider session={session}>
      <ChakraProvider>
        <DataContext.Provider
          value={{ data, setData, categories: categories ?? null }}
        >
          <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="flex min-h-screen flex-col  items-stretch bg-background pt-4">
            <Navbar />
            <div className="container mx-auto grow bg-red-500">
              <Component {...pageProps} />
            </div>
          </main>
        </DataContext.Provider>
      </ChakraProvider>
    </SessionProvider>
  );
};
export default api.withTRPC(MyApp);
