import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import Head from "next/head";
import { api } from "~/utils/api";
import { DataContext } from "./data_context";
import "~/styles/globals.css";
import Link from "next/link";
const Navbar = () => {
  return (
    <div className="navbar bg-primary text-primary relative z-40 border-b px-3 text-white sm:px-6">
      <div className="container mx-auto flex items-center justify-between">
        <h1 className="font-bold">T3 App</h1>
        <div className="-mb-px flex space-x-3 overflow-x-auto sm:space-x-0">
          <a
            className="text-primary whitespace-nowrap border-b border-blue-600 pb-2 pt-1 font-semibold leading-none transition sm:px-2"
            href="/api/auth/signin"
          >
            Dashboard
          </a>
          <Link
            className="text-primary whitespace-nowrap border-b border-transparent pb-2 pt-1 leading-none transition hover:border-gray-300 dark:hover:border-gray-600 sm:px-2"
            href="/api/auth/signin"
          >
            Sign out
          </Link>
          <a
            className="text-primary whitespace-nowrap border-b border-transparent pb-2 pt-1 leading-none transition hover:border-gray-300 dark:hover:border-gray-600 sm:px-2"
            href="/api/auth/signin"
          >
            Sign out
          </a>
        </div>
      </div>
    </div>
  );
};
import { useEffect, useState } from "react";
import { Transaction } from "./import_suite/types";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const [data, setData] = useState<Transaction[] | undefined>(undefined);
  // Load data from localStorage when component mounts
  useEffect(() => {
    const savedData = localStorage.getItem("data");
    if (savedData && savedData.length > 0) {
      console.log("Setting data", JSON.parse(savedData));
      setData(JSON.parse(savedData));
    }
  }, []);

  // Save data to localStorage whenever it changes
  useEffect(() => {
    if (data === undefined) {
      return;
    }
    localStorage.setItem("data", JSON.stringify(data));
  }, [data]);
  return (
    <SessionProvider session={session}>
      <DataContext.Provider value={{ data, setData }}>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex min-h-screen flex-col  items-stretch bg-background pt-4">
          <Navbar />
          <div className="container mx-auto grow bg-red-500">
            <Component {...pageProps} />
            <p>
              Current Number of imported transactions:{" "}
              {(data && data.length) || 0}
            </p>
          </div>
        </main>
      </DataContext.Provider>
    </SessionProvider>
  );
};
export default api.withTRPC(MyApp);
